name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
    
# 工作流是由一个或多个的jobs构成的，在jobs里来说明要交给GitHub aciton执行的任务
jobs:
  # 这个jobs中的一个任务，名字叫build(随便怎么取)
  build:
    # 用来指定这个任务在什么操作系统上跑(服务器是GitHub免费提供的)
    runs-on: ubuntu-latest
    steps:
      # 输出IP
      - name: IP
        run: sudo curl ifconfig.me
      # 首先copy git仓库到虚拟机上
      - name: Checkout
        uses: actions/checkout@v2
        # 安装初始化python
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: 'x64'
        # 安装脚本所需的依赖
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
        # 运行脚本
      - name: 'Working'
        env:	#添加环境变量
          SCKEY: ${{ secrets.SCKEY }}
          SKEY: ${{ secrets.SKEY }}
        run: python ./main.py
